"""Memory store protocol and factory."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable


@runtime_checkable
class MemoryStoreProtocol(Protocol):
    """Interface for memory persistence backends."""

    # -- Global Memory --

    def read_long_term(self) -> str: ...
    def write_long_term(self, content: str) -> None: ...
    def read_history(self) -> str: ...
    def append_history(self, entry: str) -> None: ...
    def get_memory_context(self) -> str: ...

    # -- Topic Memory --

    def read_topic_memory(self, topic: str) -> str | None: ...
    def write_topic_memory(self, topic: str, content: str) -> None: ...
    def read_topic_history(self, topic: str) -> str: ...
    def append_topic_history(self, topic: str, entry: str) -> None: ...
    def get_topic_memory_context(self, topic: str) -> str | None: ...
    def list_topics(self) -> list[str]: ...

    # -- Topic Mapping --

    def get_topic_mapping(self, chat_id: int, thread_id: int) -> str | None: ...
    def set_topic_mapping(self, chat_id: int, thread_id: int, topic_name: str) -> None: ...
    def delete_topic_mapping(self, chat_id: int, thread_id: int) -> None: ...
    def load_all_topic_mappings(self) -> dict[tuple[int, int], str]: ...

    # -- Topic Litellm Config --

    def get_topic_litellm(self, topic_name: str) -> tuple[str, float, int] | None: ...

    def set_topic_litellm(
        self, topic_name: str, model: str, temperature: float, max_tokens: int
    ) -> None: ...

    def delete_topic_litellm(self, topic_name: str) -> None: ...

    # -- Reactions & Sentiment --

    def record_reaction(
        self, chat_id: str, message_id: int, emoji: str, sentiment: str, topic: str
    ) -> None: ...
    def remove_reaction(self, chat_id: str, message_id: int, emoji: str) -> None: ...
    def get_message_sentiment(self, chat_id: str, message_id: int) -> dict[str, int]: ...
    def get_high_value_messages(self, topic: str) -> list[int]: ...
    def resolve_emoji_sentiment(self, emoji: str) -> str | None: ...
    def is_emoji_known(self, emoji: str) -> bool: ...
    def learn_emoji(self, emoji: str, sentiment: str) -> None: ...
    def cleanup_old_reactions(self, max_age_days: int = 30) -> int: ...


def create_memory_store(config: object, workspace: Path) -> MemoryStoreProtocol:
    """Create a memory store based on config.database.backend.

    Args:
        config: Config object with config.database.backend and config.database.url.
        workspace: Path to the nanobot workspace directory.
    """
    db_config = getattr(config, "database", None)
    backend = getattr(db_config, "backend", "sqlite") if db_config else "sqlite"

    if backend == "postgres":
        from nanobot.agent.store_postgres import PostgresMemoryStore

        url = getattr(db_config, "url", "")
        pool_size = getattr(db_config, "pool_size", 5)
        if not url:
            raise ValueError("database.url is required when backend is 'postgres'")
        return PostgresMemoryStore(url, pool_size=pool_size)

    from nanobot.agent.store_sqlite import SqliteMemoryStore

    return SqliteMemoryStore(workspace)
